### ISSUE TITLE
Feature Request:  Skip item during review instead of just y/n 

### ISSUE THREAD

**Issue by ybisk** [allenai/amti#6]
If you want to think about an option before deciding if it's rejection worthy it'd be nice to be able to go through the rest of this HITs first.  Maybe also worth adding a way to mark that maybe even if you accept, this is an item you'd later like to remove from your dataset?

**Comment by nalourie-ai2** [comment]
This issue has been fully addressed by [PR #22](https://github.com/allenai/amti/pull/22).
