### ISSUE TITLE
TypeError: write() argument must be str, not None in amti/actions/create.py

### ISSUE THREAD

**Issue by keisks** [allenai/amti#9]
https://github.com/allenai/amti/blob/1e156b01702e098811bd43c314bc4f2b5dbbfa06/amti/actions/create.py#L81

If the `current_commit` is `None`, we get a TypeError. 

    TypeError: write() argument must be str, not None

**Comment by keisks** [comment]
My current workaround is to `git clone` amti (in addition to `pip install`) and run experiments under the amti directory, although I am not sure if this is the best.

**Comment by nalourie-ai2** [comment]
This issue has been addressed by PR https://github.com/allenai/amti/pull/18.
